#!/bin/bash
# Combined provisioning script for ComfyUI with comfy-cli
# Generated by upload_provisioning_script.py

echo "=== Starting ComfyUI Provisioning ==="
echo "Time: $(date)"

# Install comfy-cli
echo "Installing comfy-cli..."
pip install --upgrade pip
pip install comfy-cli

# Verify comfy-cli installation
if command -v comfy &> /dev/null; then
    echo "✅ comfy-cli installed successfully"
    comfy --version
else
    echo "❌ comfy-cli installation failed"
fi

# Run the original provisioning script if it exists
if [ -f "/tmp/provisioning.sh" ]; then
    echo "Running original provisioning script..."
    bash /tmp/provisioning.sh
else
    # Default ComfyUI setup
    cd /workspace
    
    # Set ComfyUI workspace
    if [ -d "/workspace/ComfyUI" ]; then
        comfy set-default /workspace/ComfyUI
        echo "✅ Set default workspace to /workspace/ComfyUI"
    fi
    
    # Show environment
    echo "=== Environment Info ==="
    comfy env || true
    
    # List nodes
    echo "=== Installed Nodes ==="
    comfy node show --installed || true
fi

echo "=== Provisioning Complete ==="
echo "Time: $(date)"
